owner: HarshZetigon
repo: Fundnation-Status

sites:
  - name: Fundnation Platform
    url: https://staging.fundnation.cloud
  - name: Database
    url: https://staging.fundnation.cloud/api/status?check=database
  - name: Storage
    url: https://staging.fundnation.cloud/api/status?check=storage
  - name: Bunny Storage
    url: https://staging.fundnation.cloud/api/status?check=bunny_storage
  - name: Bunny CDN
    url: https://staging.fundnation.cloud/api/status?check=bunny_cdn
  - name: Cron - Exchange Rates
    url: https://staging.fundnation.cloud/api/status?check=cron_exchange_rates
  - name: Stripe
    url: https://staging.fundnation.cloud/api/status?check=stripe
  - name: Paystack
    url: https://staging.fundnation.cloud/api/status?check=paystack
  - name: Mailgun
    url: https://staging.fundnation.cloud/api/status?check=mailgun
  - name: SendPulse
    url: https://staging.fundnation.cloud/api/status?check=sendpulse
  - name: Zetigon SMS
    url: https://staging.fundnation.cloud/api/status?check=zetigon_sms
  - name: FreeCurrency API
    url: https://staging.fundnation.cloud/api/status?check=freecurrency_api

status-website:
  baseUrl: /Fundnation-Status
  name: Fundnation Status
  theme: dark
